name: Run Terraform for Repository Creation

on:
  push:
    branches:
      - "main"
    paths:
      - 'Setting/prod/repository/**'

permissions: read-all
jobs:
  Terraform-Script:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Use Terraform Init Steps
        uses: ./.github/workflows/steps/terraform_init.yml
        with:
          backend-conf-secret: ${{ secrets.TF_BACKEND_CONF }}
          working-directory: ./Setting/prod/repository
