name: Run Terraform For Team Repository Permissions

on:
  push:
    branches:
    - "main"
    paths:
    - 'Setting/prod/team_member/**'

permissions: read-all
jobs:
  Terraform-Script:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Use Terraform Init Steps
        uses: ./.github/workflows/steps/terraform_init.yml
        with:
          backend-conf-secret: ${{ secrets.TF_BACKEND_CONF_FOR_TEAM_REPOSITORY }}
          working-directory: ./Setting/prod/team_member
