# team:
ALL3:          
  member:
    p_so: "member"           
  closed: false           
  parent_team:       
  description: 

SWE3:          
  member:
    SanyaTangook: "maintainer"
    Nutty: "member"
    dmakeroam: "member"             
  closed: true          
  parent_team: "datax-all"       
  description:  

DBA3:
  member:
    SanyaTangook: "maintainer"
    dmakeroam: "maintainer"
    p_so: "member"           
  closed: true           
  parent_team: "datax-all"       
  description:    