name: Run Terraform Setting

on:
  push:
    branches:
    - "main"
    paths:
    - 'Setting/prod/repository/**'

permissions: read-all
jobs:
    Terraform-Script:
        runs-on: ubuntu-22.04
        defaults:
          run:
            working-directory: ./Setting/prod/repository
        steps:
        - name: code checkout
          uses: actions/checkout@v3

        - name: setup terraform
          uses: hashicorp/setup-terraform@v1
          with:
            terraform_version: ${{vars.tf_version}}

        - name: read terraform backend configuration
          uses: mobiledevops/secret-to-file-action@v1
          with:
            base64-encoded-secret: ${{ secrets.tf_backend_conf }}
            filename: "backend.conf"
            is-executable: false

        - name: terraform init
          id: init
          run: terraform init -input=false -backend-config=backend.conf

        - name: code security scan
          id: checkov
          uses: bridgecrewio/checkov-action@master
          with:
            framework: terraform

        - name: terraform validate
          id: validate
          run: terraform validate -no-color

        - name: terraform plan
          id: plan
          run: terraform plan -no-color -input=false
          env:
            TF_VAR_github_org_token: ${{secrets.github_org_token}}
            TF_VAR_github_org_name: ${{vars.github_org_name}}

        - name: terraform apply
          id: apply
          run: terraform apply -input=false -auto-approve
          env:
            TF_VAR_github_org_token: ${{secrets.github_org_token}}
            TF_VAR_github_org_name: ${{vars.github_org_name}}
